apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-99
  name: demo-99
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-99
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-99
    spec:
      containers:
      - image: arunkumarshahi/ak-docker-demo
        name: demo-99
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-99
  name: demo-99
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}